Vagrant.configure("2") do |config|
    config.vm.define 'kube-base' do |nodeconfig|
        nodeconfig.vm.box = 'ubuntu/bionic64'
        nodeconfig.vm.hostname = 'kube-base'
        
        # Virtual hardware configuration
        nodeconfig.vm.provider "virtualbox" do |v|
            v.memory = 2000
            v.cpus = 2
            v.default_nic_type = "virtio"
            v.linked_clone = true
        end
        
        nodeconfig.vm.provision "shell", path: 'provision.sh'
    end
end
